### ISSUE TITLE
Move database config to env vars

### ISSUE THREAD

**Issue by halfer** [halfer/awooga-app#2]
The database configuration is hardwired whilst the project is in prototype stage, need to move this to vhost config.

**Comment by PeeHaa** [comment]
Please reconsider this. Not everybody has control over the vhosts and not everybody can or wants to use .htaccess files.

Instead I would suggest to use some config file in the root of the project instead that gets included.

**Comment by halfer** [comment]
I've made a couple of fixes here

* Test connection credentials now come from file config, previously hardwired
* SSO config can now be set in file config instead,previously vhost only

@PeeHaa: I will probably still support vhost variable database settings in the future, but if I do that it will be an addition rather than a replacement for file config.
