### ISSUE TITLE
Edit reports in website

### ISSUE THREAD

**Issue by halfer** [halfer/awooga-app#7]
@PeeHaa contributed the following issue on the old repo (now my reports repo):

>  Imho setting up a proper website makes it a lot more easier for people to contribute and makes it easier for people to validate the reviews.
>
> I have also been playing with this idea for a long time and have talked about this with a couple of people. My conclusion with all this talk was that I was willing to try out a StackOverflow model for validating reviews and reviewing tutorials.
>
> The game element (if set up correctly) will help get and keep contributors and the voting system might have validating it.
>
> I think the hardest part is getting the firs smart people on board and spending their valuable time on contributing.

**Comment by PeeHaa** [comment]
I just searched for a tutorial which was not yet in the system. I would really love to at least have a way to add it from the site.

**Comment by halfer** [comment]
Hi @PeeHaa, that is coming soon. I've added a OAuth system and expect to have it operational next week.

**Comment by PeeHaa** [comment]
:heart:

**Comment by halfer** [comment]
The code for this is pretty much done, but it needs a set of functional tests. I'll try to make a start on those tomorrow.

The help panels on the home page and on the FAQ page will need updating for this ticket.

**Comment by halfer** [comment]
@PeeHaa: I've deployed a new version, and it seems to be working OK on GitHub SSO. Bear in mind deletion hasn't been implemented, and on a similar note I've suggested a published flag (#11).

There's no creation date yet, as this wasn't a priority for repo-originated reports. I'll add that next.
